// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPnNvbqFCnoK7TlkajDoONLDMVrpDuTbU',
    appId: '1:269447796570:web:5b6f456a776dc610668563',
    messagingSenderId: '269447796570',
    projectId: 'viexplorer-79fa7',
    authDomain: 'viexplorer-79fa7.firebaseapp.com',
    storageBucket: 'viexplorer-79fa7.appspot.com',
    measurementId: 'G-BV46NJ6KV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-wzwUdHCdon8kW072wXdMYHRYqbf9zU0',
    appId: '1:269447796570:android:9bc1ba8025895d2e668563',
    messagingSenderId: '269447796570',
    projectId: 'viexplorer-79fa7',
    storageBucket: 'viexplorer-79fa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJJs9IoXii_5Rt4YhGMJTskVZJHN6HEMo',
    appId: '1:269447796570:ios:f990301ae34ee038668563',
    messagingSenderId: '269447796570',
    projectId: 'viexplorer-79fa7',
    storageBucket: 'viexplorer-79fa7.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJJs9IoXii_5Rt4YhGMJTskVZJHN6HEMo',
    appId: '1:269447796570:ios:f399befdc55ff518668563',
    messagingSenderId: '269447796570',
    projectId: 'viexplorer-79fa7',
    storageBucket: 'viexplorer-79fa7.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
